version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm install --prefix perfanalyticsdashboard
      - run: npm run build --prefix perfanalyticsdashboard
      - run: npm run build
